name: Font Optimization

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2
                    
            - name: Use Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8' 
                  run: 
                      pip install fontTools cos-python-sdk-v5 brotli

            - name: Font Optimization
              run: |
                 python scripts/minfont.py
                 python scripts/uFont.py
